### PR TITLE
Add option to specify the resolution through the command line.

### PR DESCRIPTION
**Pull request by domoritz**
Also change dpi to be an int.

### CODE REVIEW

**Comment by chrisc36** [comment]
Thanks for your contributions, also sorry for being so spotty when it comes to keeping track of my pull requests. I am hesitant to merge this commit because change the resolution will throw off the rather brittlely selected thresholds throughout of the rest of the code that are often set using pixels, so if the user changes the resolution performance will likely be very poor.

**Comment by domoritz** [comment]
Hmm, okay. What I need is a higher resolution for the output images. Maybe I should change the code so that only the output image is affected.

**Comment by domoritz** [comment]
@chrisc36 So I guess the best thing for my use case is to render the images myself. However, wouldn't it be useful to be able to set the dpi given that there are thresholds in the code that depend on it?

**Comment by chrisc36** [comment]
I am worried that it would be confusing to have a DPI option since users will probably assume, like you did, it will only change the output format not how the algorithm behaves. In general there are (a lot!) of thresholds that one could tune. The right way to handle this would be to have a proper config file, but short of that my feeling is that it is best to avoid cluttering the CLI with a ton of threshold options.

**Pull request closed without merging**
